const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Exps.Text,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Timer: 0},
	{Border: 0},
	{TopText: 0},
	{Scanline2: 0},
	{Selector: 0},
	{Location: 0},
	{SelectText1: 0},
	{Keyboard: 0},
	{InputText: 0},
	{Flash: 0},
	{Blinking: 0},
	{ReportText: 0},
	{SideText: 0},
	{OutputText: 0},
	{OutputText2: 0},
	{MakeMyOwnArrayIGues: 0},
	{ADMINTEXT1: 0},
	{ADMINTEXT2: 0},
	{Browser: 0},
	{SelectionNumber: 0},
	{PageLocation: 0},
	{HighestSelection: 0},
	{SelectionChangedBool: 0},
	{LastKey: 0},
	{InputString: 0},
	{EnterPressed: 0},
	{Fullscreen: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Border: class extends self.ISpriteInstance {},
	TopText: class extends self.ITextInstance {},
	Scanline2: class extends self.ITiledBackgroundInstance {},
	SelectText1: class extends self.ITextInstance {},
	Selector: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	InputText: class extends self.ITextInstance {},
	Blinking: class extends self.ISpriteInstance {},
	ReportText: class extends self.ITextInstance {},
	SideText: class extends self.ITextInstance {},
	MakeMyOwnArrayIGues: class extends self.ISpriteInstance {},
	ADMINTEXT1: class extends self.ITextInstance {},
	ADMINTEXT2: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {}
}